FROM docker.io/maven:3.8.3-adoptopenjdk-11 AS build
LABEL stage=build
COPY src/backend/src /home/polliti_backend/src
COPY src/backend/pom.xml /home/polliti_backend
RUN mvn -f /home/polliti_backend/pom.xml clean package

FROM docker.io/adoptopenjdk/openjdk11:alpine
RUN apk add --no-cache libx11 mesa-gl gtk+3.0 xvfb ttf-dejavu
ENV DISPLAY=:99
COPY --from=build /home/polliti_backend/target/polliti-0.0.1-SNAPSHOT.jar /usr/local/lib/polliti/polliti_backend.jar
EXPOSE 8080

CMD rm -f /tmp/.X99-lock ; Xvfb :99 & java -jar /usr/local/lib/polliti/polliti_backend.jar --spring.config.location=/usr/local/lib/polliti/application.properties